/** biome-ignore-all lint/suspicious/noExplicitAny: Unexpected any. Specify a different type. */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react"

export const Index: Record<string, any> = {
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [
      {
        path: "src/registry/src/lib/utils.ts",
        type: "registry:lib",
      },
    ],
  },
  metadata: {
    name: "metadata",
    description: "",
    type: "registry:lib",
    files: [
      {
        path: "src/registry/lib/metadata.ts",
        type: "registry:lib",
      },
    ],
  },
  sanitize: {
    name: "sanitize",
    description: "",
    type: "registry:lib",
    files: [
      {
        path: "src/registry/src/utils/sanitize.ts",
        type: "registry:lib",
      },
    ],
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    files: [
      {
        path: "src/registry/src/hooks/use-mobile.ts",
        type: "registry:hook",
      },
    ],
  },
  "use-data-table": {
    name: "use-data-table",
    description: "",
    type: "registry:hook",
    files: [
      {
        path: "src/registry/hooks/use-data-table.ts",
        type: "registry:hook",
      },
    ],
  },
  "adminsys-auth": {
    name: "adminsys-auth",
    description: "",
    type: "registry:block",
    files: [
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/error/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/forgot-password/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/components/auth/form/forgot-password-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/forgot-password.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/new-verification/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/components/auth/form/new-verification-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/reset-password/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/components/auth/form/reset-password-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/reset-password.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/sign-in/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/auth/sign-up/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/privacy-policy/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/terms-of-service/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/settings/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/settings/account/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/components/auth/form/account-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/account-image-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/delete-account-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/account.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/examples/adminsys-auth/app/(home)/settings/profile/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/components/auth/card/card-user-profile.tsx",
        type: "registry:component",
      },
    ],
  },
  adminsys: {
    name: "adminsys",
    description: "",
    type: "registry:block",
    files: [
      {
        path: "src/registry/examples/adminsys/app/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/not-found.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/sitemap.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(home)/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(home)/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/config/types/index.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/config/validation/env.schema.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/config/validation/site-config.schema.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/config/env.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/config/site-config.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(admin)/admin/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(admin)/admin/dashboard/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(admin)/admin/folder-01/submenu-01/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/adminsys/app/(admin)/admin/folder-01/submenu-02/page.tsx",
        type: "registry:file",
      },
    ],
  },
  sitesys: {
    name: "sitesys",
    description: "",
    type: "registry:block",
    files: [
      {
        path: "src/registry/examples/sitesys/app/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/app/sitemap.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/app/(home)/layout.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/app/(home)/page.tsx",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/config/types/index.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/config/validation/env.schema.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/config/validation/site-config.schema.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/config/env.ts",
        type: "registry:file",
      },
      {
        path: "src/registry/examples/sitesys/config/site-config.tsx",
        type: "registry:file",
      },
    ],
  },
  "dropdown-user": {
    name: "dropdown-user",
    description: "A dropdown-user component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/auth/dropdown/dropdown-user.tsx",
        type: "registry:component",
      },
    ],
  },
  "form-auth": {
    name: "form-auth",
    description: "A form-auth component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/auth/card/card-auth-wrapper.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/dialog/terms-and-policy-dialog.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/social-login.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/sign-in-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/auth-base.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/sign-in.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/sign-up-form.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/validations/auth/sign-up.schema.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/components/auth/form/form-auth.tsx",
        type: "registry:component",
      },
    ],
  },
  "admin-navbar": {
    name: "admin-navbar",
    description: "A admin-navbar component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/navbar/admin-navbar.tsx",
        type: "registry:component",
      },
    ],
  },
  "admin-sidebar": {
    name: "admin-sidebar",
    description: "A admin-sidebar component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/sidebar/inc/part/sidebar-menu-folder.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/inc/part/sidebar-menu-link.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/inc/part/sidebar-submenu-link.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/inc/sidebar-nav-main.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/inc/sidebar-nav-secondary.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/inc/sidebar-nav-user.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/sidebar/admin-sidebar.tsx",
        type: "registry:component",
      },
    ],
  },
  "admin-layout": {
    name: "admin-layout",
    description: "A admin-layout component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/admin-layout/index.tsx",
        type: "registry:component",
      },
    ],
  },
  banner: {
    name: "banner",
    description: "A banner component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/banner/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "footer-01": {
    name: "footer-01",
    description: "A footer-01 component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/footer/footer-01.tsx",
        type: "registry:component",
      },
    ],
  },
  "hero-01": {
    name: "hero-01",
    description: "A hero-01 component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/hero/hero-01.tsx",
        type: "registry:component",
      },
    ],
  },
  "navbar-01": {
    name: "navbar-01",
    description: "A navbar-01 component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/navbar/inc/nav-main.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/inc/nav-mobile.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/inc/nav-system.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/types/index.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/navbar-01.tsx",
        type: "registry:component",
      },
    ],
  },
  "navbar-auth-01": {
    name: "navbar-auth-01",
    description: "A navbar-auth-01 component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/navbar/inc/nav-main-auth.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/inc/nav-mobile-auth.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/inc/nav-system.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/types/index.ts",
        type: "registry:component",
      },
      {
        path: "src/registry/components/layout/navbar/navbar-auth-01.tsx",
        type: "registry:component",
      },
    ],
  },
  "auth-layout": {
    name: "auth-layout",
    description: "A auth-layout component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/auth-layout/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "site-layout": {
    name: "site-layout",
    description: "A site-layout component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/layout/site-layout/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "tailwind-indicator": {
    name: "tailwind-indicator",
    description: "A tailwind-indicator component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/dev/tailwind-indicator.tsx",
        type: "registry:component",
      },
    ],
  },
  "alert-error": {
    name: "alert-error",
    description: "A alert-error component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/alert/alert-error.tsx",
        type: "registry:component",
      },
    ],
  },
  "alert-info": {
    name: "alert-info",
    description: "A alert-info component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/alert/alert-info.tsx",
        type: "registry:component",
      },
    ],
  },
  "alert-success": {
    name: "alert-success",
    description: "A alert-success component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/alert/alert-success.tsx",
        type: "registry:component",
      },
    ],
  },
  "alert-warn": {
    name: "alert-warn",
    description: "A alert-warn component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/alert/alert-warn.tsx",
        type: "registry:component",
      },
    ],
  },
  container: {
    name: "container",
    description: "A container component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/container/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "data-table": {
    name: "data-table",
    description: "A data-table component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/data-table/index.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/part/data-table-faceted-filter.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/part/data-table-row-actions.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/part/data-table-search-input.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/part/data-table-toggle-columns.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/part/data-table-view-options.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/data-table-column-header.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/data-table-pagination.tsx",
        type: "registry:component",
      },
      {
        path: "src/registry/components/shared/data-table/inc/data-table-toolbar.tsx",
        type: "registry:component",
      },
    ],
  },
  "delete-confirmation-dialog": {
    name: "delete-confirmation-dialog",
    description: "A delete-confirmation-dialog component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/dialog/delete-confirmation-dialog.tsx",
        type: "registry:component",
      },
    ],
  },
  "details-dialog": {
    name: "details-dialog",
    description: "A details-dialog component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/dialog/details-dialog.tsx",
        type: "registry:component",
      },
    ],
  },
  "form-dialog": {
    name: "form-dialog",
    description: "A form-dialog component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/dialog/form-dialog.tsx",
        type: "registry:component",
      },
    ],
  },
  "password-input": {
    name: "password-input",
    description: "A password-input component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/form/password-input/index.tsx",
        type: "registry:component",
      },
    ],
  },
  icons: {
    name: "icons",
    description: "A icons component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/icons/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "loading-spinner": {
    name: "loading-spinner",
    description: "A loading-spinner component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/loading/loading-spinner.tsx",
        type: "registry:component",
      },
    ],
  },
  "logo-adminsys": {
    name: "logo-adminsys",
    description: "A logo-adminsys component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/logo/logo-adminsys.tsx",
        type: "registry:component",
      },
    ],
  },
  "logo-docsys": {
    name: "logo-docsys",
    description: "A logo-docsys component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/logo/logo-docsys.tsx",
        type: "registry:component",
      },
    ],
  },
  "logo-sitesys": {
    name: "logo-sitesys",
    description: "A logo-sitesys component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/logo/logo-sitesys.tsx",
        type: "registry:component",
      },
    ],
  },
  "not-found": {
    name: "not-found",
    description: "A not-found component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/not-found/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "theme-provider": {
    name: "theme-provider",
    description: "A theme-provider component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/provider/theme-provider.tsx",
        type: "registry:component",
      },
    ],
  },
  "social-icon-link": {
    name: "social-icon-link",
    description: "A social-icon-link component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/social/social-icon-link.tsx",
        type: "registry:component",
      },
    ],
  },
  "theme-toggle": {
    name: "theme-toggle",
    description:
      "A theme-toggle component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/toggle/theme-toggle.tsx",
        type: "registry:component",
      },
    ],
  },
  "toggle-theme": {
    name: "toggle-theme",
    description:
      "A toggle-theme component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/toggle/toggle-theme.tsx",
        type: "registry:component",
      },
    ],
  },
  typography: {
    name: "typography",
    description: "A typography component.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/shared/typography/index.tsx",
        type: "registry:component",
      },
    ],
  },
  "form-auth-demo": {
    name: "form-auth-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/auth/form/form-auth-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import("@/registry/examples/components/auth/form/form-auth-demo.tsx")
    ),
  },
  "dropdown-user-demo": {
    name: "dropdown-user-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/auth/dropdown/dropdown-user-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/auth/dropdown/dropdown-user-demo.tsx"
        )
    ),
  },
  "admin-navbar-demo": {
    name: "admin-navbar-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/navbar/admin-navbar-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/layout/navbar/admin-navbar-demo.tsx"
        )
    ),
  },
  "banner-demo": {
    name: "banner-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/banner/banner-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import("@/registry/examples/components/layout/banner/banner-demo.tsx")
    ),
  },
  "footer-01-demo": {
    name: "footer-01-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/footer/footer-01-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/layout/footer/footer-01-demo.tsx"
        )
    ),
  },
  "hero-01-demo": {
    name: "hero-01-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/hero/hero-01-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import("@/registry/examples/components/layout/hero/hero-01-demo.tsx")
    ),
  },
  "navbar-01-demo": {
    name: "navbar-01-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/navbar/navbar-01-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/layout/navbar/navbar-01-demo.tsx"
        )
    ),
  },
  "navbar-auth-01-demo": {
    name: "navbar-auth-01-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/layout/navbar/navbar-auth-01-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/layout/navbar/navbar-auth-01-demo.tsx"
        )
    ),
  },
  "tailwind-indicator-demo": {
    name: "tailwind-indicator-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/dev/tailwind-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import("@/registry/examples/components/dev/tailwind-indicator-demo.tsx")
    ),
  },
  "alert-error-demo": {
    name: "alert-error-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/alert/alert-error-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/alert/alert-error-demo.tsx"
        )
    ),
  },
  "alert-info-demo": {
    name: "alert-info-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/alert/alert-info-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/alert/alert-info-demo.tsx"
        )
    ),
  },
  "alert-success-demo": {
    name: "alert-success-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/alert/alert-success-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/alert/alert-success-demo.tsx"
        )
    ),
  },
  "alert-warn-demo": {
    name: "alert-warn-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/alert/alert-warn-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/alert/alert-warn-demo.tsx"
        )
    ),
  },
  "container-demo": {
    name: "container-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/container/container-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/container/container-demo.tsx"
        )
    ),
  },
  "password-input-demo": {
    name: "password-input-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/form/password-input-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/form/password-input-demo.tsx"
        )
    ),
  },
  "loading-spinner-demo": {
    name: "loading-spinner-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/loading/loading-spinner-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/loading/loading-spinner-demo.tsx"
        )
    ),
  },
  "icons-demo": {
    name: "icons-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/icons/icons-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () => import("@/registry/examples/components/shared/icons/icons-demo.tsx")
    ),
  },
  "logo-adminsys-demo": {
    name: "logo-adminsys-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/logo/logo-adminsys-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/logo/logo-adminsys-demo.tsx"
        )
    ),
  },
  "logo-docsys-demo": {
    name: "logo-docsys-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/logo/logo-docsys-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/logo/logo-docsys-demo.tsx"
        )
    ),
  },
  "logo-sitesys-demo": {
    name: "logo-sitesys-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/logo/logo-sitesys-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/logo/logo-sitesys-demo.tsx"
        )
    ),
  },
  "not-found-demo": {
    name: "not-found-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/not-found/not-found-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/not-found/not-found-demo.tsx"
        )
    ),
  },
  "social-icon-link-demo": {
    name: "social-icon-link-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/social/social-icon-link-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/social/social-icon-link-demo.tsx"
        )
    ),
  },
  "theme-toggle-demo": {
    name: "theme-toggle-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/toggle/theme-toggle-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/toggle/theme-toggle-demo.tsx"
        )
    ),
  },
  "toggle-theme-demo": {
    name: "toggle-theme-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/toggle/toggle-theme-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/toggle/toggle-theme-demo.tsx"
        )
    ),
  },
  "typography-demo": {
    name: "typography-demo",
    description: "",
    type: "registry:example",
    files: [
      {
        path: "src/registry/examples/components/shared/typography/typography-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(
      () =>
        import(
          "@/registry/examples/components/shared/typography/typography-demo.tsx"
        )
    ),
  },
}
