
/** biome-ignore-all lint/suspicious/noExplicitAny: Unexpected any. Specify a different type. */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "metadata": {
    name: "metadata",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/metadata.ts",
      type: "registry:lib",
    }],
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-mobile.ts",
      type: "registry:hook",
    }],
  },
  "sitesys": {
    name: "sitesys",
    description: "",
    type: "registry:block",
    files: [{
      path: "src/registry/examples/sitesys/app/layout.tsx",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/app/(home)/layout.tsx",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/app/(home)/page.tsx",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/config/types/index.ts",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/config/validation/env.schema.ts",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/config/validation/site-config.schema.ts",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/config/env.ts",
      type: "registry:file",
    },{
      path: "src/registry/examples/sitesys/config/site-config.tsx",
      type: "registry:file",
    }],
  },
  "banner": {
    name: "banner",
    description: "A banner component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/banner/index.tsx",
      type: "registry:component",
    }],
  },
  "container": {
    name: "container",
    description: "A container component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/container/index.tsx",
      type: "registry:component",
    }],
  },
  "footer-01": {
    name: "footer-01",
    description: "A footer-01 component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/footer/footer-01.tsx",
      type: "registry:component",
    }],
  },
  "hero-01": {
    name: "hero-01",
    description: "A hero-01 component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/hero/hero-01.tsx",
      type: "registry:component",
    }],
  },
  "icons": {
    name: "icons",
    description: "A icons component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/icons/index.tsx",
      type: "registry:component",
    }],
  },
  "logo-adminsys": {
    name: "logo-adminsys",
    description: "A logo-adminsys component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/logo/logo-adminsys.tsx",
      type: "registry:component",
    }],
  },
  "logo-docsys": {
    name: "logo-docsys",
    description: "A logo-docsys component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/logo/logo-docsys.tsx",
      type: "registry:component",
    }],
  },
  "logo-sitesys": {
    name: "logo-sitesys",
    description: "A logo-sitesys component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/logo/logo-sitesys.tsx",
      type: "registry:component",
    }],
  },
  "navbar-01": {
    name: "navbar-01",
    description: "A navbar-01 component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/navbar/inc/nav-main.tsx",
      type: "registry:component",
    },{
      path: "src/registry/components/layout/navbar/inc/nav-mobile.tsx",
      type: "registry:component",
    },{
      path: "src/registry/components/layout/navbar/inc/nav-system.tsx",
      type: "registry:component",
    },{
      path: "src/registry/components/layout/navbar/types/index.ts",
      type: "registry:component",
    },{
      path: "src/registry/components/layout/navbar/navbar-01.tsx",
      type: "registry:component",
    }],
  },
  "not-found": {
    name: "not-found",
    description: "A not-found component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/not-found/index.tsx",
      type: "registry:component",
    }],
  },
  "theme-provider": {
    name: "theme-provider",
    description: "A theme-provider component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/provider/theme-provider.tsx",
      type: "registry:component",
    }],
  },
  "site-layout": {
    name: "site-layout",
    description: "A site-layout component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/site-layout/index.tsx",
      type: "registry:component",
    }],
  },
  "social-icon-link": {
    name: "social-icon-link",
    description: "A social-icon-link component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/social/social-icon-link.tsx",
      type: "registry:component",
    }],
  },
  "tailwind-indicator": {
    name: "tailwind-indicator",
    description: "A tailwind-indicator component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/dev/tailwind-indicator.tsx",
      type: "registry:component",
    }],
  },
  "theme-toggle": {
    name: "theme-toggle",
    description: "A theme-toggle component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/toggle/theme-toggle.tsx",
      type: "registry:component",
    }],
  },
  "toggle-theme": {
    name: "toggle-theme",
    description: "A toggle-theme component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/toggle/toggle-theme.tsx",
      type: "registry:component",
    }],
  },
  "typography": {
    name: "typography",
    description: "A typography component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/typography/index.tsx",
      type: "registry:component",
    }],
  },
  "banner-demo": {
    name: "banner-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/banner/banner-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/banner/banner-demo.tsx")),

  },
  "container-demo": {
    name: "container-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/container/container-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/container/container-demo.tsx")),

  },
  "footer-01-demo": {
    name: "footer-01-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/footer/footer-01-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/footer/footer-01-demo.tsx")),

  },
  "hero-01-demo": {
    name: "hero-01-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/hero/hero-01-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/hero/hero-01-demo.tsx")),

  },
  "icons-demo": {
    name: "icons-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/icons/icons-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/icons/icons-demo.tsx")),

  },
  "logo-adminsys-demo": {
    name: "logo-adminsys-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/logo/logo-adminsys-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/logo/logo-adminsys-demo.tsx")),

  },
  "logo-docsys-demo": {
    name: "logo-docsys-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/logo/logo-docsys-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/logo/logo-docsys-demo.tsx")),

  },
  "logo-sitesys-demo": {
    name: "logo-sitesys-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/logo/logo-sitesys-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/logo/logo-sitesys-demo.tsx")),

  },
  "navbar-01-demo": {
    name: "navbar-01-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/navbar/navbar-01-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/navbar/navbar-01-demo.tsx")),

  },
  "not-found-demo": {
    name: "not-found-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/not-found/not-found-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/not-found/not-found-demo.tsx")),

  },
  "typography-demo": {
    name: "typography-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/typography/typography-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/typography/typography-demo.tsx")),

  },
  "social-icon-link-demo": {
    name: "social-icon-link-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/social/social-icon-link-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/social/social-icon-link-demo.tsx")),

  },
  "tailwind-indicator-demo": {
    name: "tailwind-indicator-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/dev/tailwind-indicator-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/dev/tailwind-indicator-demo.tsx")),

  },
  "theme-toggle-demo": {
    name: "theme-toggle-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/toggle/theme-toggle-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/toggle/theme-toggle-demo.tsx")),

  },
  "toggle-theme-demo": {
    name: "toggle-theme-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/toggle/toggle-theme-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/toggle/toggle-theme-demo.tsx")),

  },
}