
/** biome-ignore-all lint/suspicious/noExplicitAny: Unexpected any. Specify a different type. */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/registry/src/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/src/hooks/use-mobile.ts",
      type: "registry:hook",
    }],
  },
  "banner": {
    name: "banner",
    description: "A banner component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/banner/index.tsx",
      type: "registry:component",
    }],
  },
  "container": {
    name: "container",
    description: "A container component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/container/index.tsx",
      type: "registry:component",
    }],
  },
  "tailwind-indicator": {
    name: "tailwind-indicator",
    description: "A tailwind-indicator component.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/dev/tailwind-indicator.tsx",
      type: "registry:component",
    }],
  },
  "theme-toggle": {
    name: "theme-toggle",
    description: "A theme-toggle component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/toggle/theme-toggle.tsx",
      type: "registry:component",
    }],
  },
  "toggle-theme": {
    name: "toggle-theme",
    description: "A toggle-theme component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/layout/toggle/toggle-theme.tsx",
      type: "registry:component",
    }],
  },
  "banner-demo": {
    name: "banner-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/banner/banner-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/banner/banner-demo.tsx")),

  },
  "container-demo": {
    name: "container-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/container/container-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/container/container-demo.tsx")),

  },
  "tailwind-indicator-demo": {
    name: "tailwind-indicator-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/dev/tailwind-indicator-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/dev/tailwind-indicator-demo.tsx")),

  },
  "theme-toggle-demo": {
    name: "theme-toggle-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/toggle/theme-toggle-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/toggle/theme-toggle-demo.tsx")),

  },
  "toggle-theme-demo": {
    name: "toggle-theme-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/components/layout/toggle/toggle-theme-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/components/layout/toggle/toggle-theme-demo.tsx")),

  },
}