import type { Registry } from "shadcn/schema"

import { components } from "./registry-components"
import { examples } from "./registry-examples"
import { hook } from "./registry-hook"
import { lib } from "./registry-lib"

/**
 * Este arquivo atua como o ponto de entrada principal para o registro de componentes do projeto.
 * Ele agrega metadados de diferentes categorias (componentes, exemplos, hooks e bibliotecas)
 * em um único objeto `registry`.
 * Este objeto é então utilizado pelo script de construção do registro (`build-registry.mts`)
 * para gerar os arquivos `index.tsx` e `registry.autogenerated.json`.
 */
export const registry = {
  name: "MaskSysDev",
  homepage: "https://adminsys-components.vercel.app/components",
  /**
   * A lista consolidada de todos os itens do registro.
   * A ordem aqui pode influenciar a ordem em que os itens aparecem em listagens ou documentações.
   */
  items: [
    // Bibliotecas de utilidade
    ...lib,
    // Hooks personalizados
    ...hook,
    // Componentes de UI
    ...components,

    // Exemplos de uso dos componentes (uso interno, geralmente não listados publicamente)
    ...examples,
  ],
} satisfies Registry
