import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para as bibliotecas de utilidade do projeto.
 * Cada objeto no array representa uma biblioteca e suas propriedades, como nome, tipo,
 * título, autor, dependências e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`,
 * permitindo a organização e o acesso centralizado às utilidades.
 */
export const lib: Registry["items"] = [
  /**
   * Biblioteca `utils`:
   * Contém funções utilitárias gerais, como `cn` para manipulação de classes CSS com `clsx` e `tailwind-merge`.
   */
  {
    name: "utils",
    type: "registry:lib",
    title: "Utility Functions",
    author: "<author> <<authorUrl>>",
    dependencies: ["clsx", "tailwind-merge"],
    files: [
      {
        path: "src/lib/utils.ts",
        type: "registry:lib",
      },
    ],
  },
  /**
   * Biblioteca `cn`:
   * Contém funções utilitárias gerais, como `cn` para manipulação de classes CSS com `clsx` e `tailwind-merge`.
   */
  {
    name: "cn",
    type: "registry:lib",
    title: "Utility Functions",
    author: "<author> <<authorUrl>>",
    dependencies: ["clsx", "tailwind-merge"],
    files: [
      {
        path: "lib/cn.ts",
        type: "registry:lib",
      },
    ],
  },
  /**
   * Biblioteca `metadata`:
   * Contém funções para gerar os metadados.
   */
  {
    name: "metadata",
    type: "registry:lib",
    title: "Metadata Functions",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "lib/metadata.ts",
        type: "registry:lib",
      },
    ],
  },
  /**
   * Biblioteca `sanitize`:
   * Contém funções utilitárias para sanitizar os dados.
   */
  {
    name: "sanitize",
    type: "registry:lib",
    title: "Sanitize Functions",
    author: "<author> <<authorUrl>>",
    dependencies: ["zod"],
    files: [
      {
        path: "utils/sanitize.ts",
        type: "registry:lib",
        target: "src/utils/sanitize.ts",
      },
    ],
  },
]
