import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os componentes de UI do projeto.
 * Cada objeto no array representa um componente e suas propriedades, como nome, tipo, descrição,
 * autor, dependências e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`.
 */
export const components: Registry["items"] = [
  /**
   * Componente `tailwind-indicator`:
   * Um indicador visual para ambientes de desenvolvimento que mostra o breakpoint atual do Tailwind CSS.
   */
  {
    name: "tailwind-indicator",
    type: "registry:component",
    description: "A tailwind-indicator component for Next.js apps.",
    title: "tailwind-indicator",
    author: "MaskSysDev <adminsys-components.vercel.app>",
    files: [
      {
        path: "components/dev/tailwind-indicator.tsx",
        type: "registry:component",
        target: "src/components/dev/tailwind-indicator.tsx",
      },
    ],
    docs: "https://adminsys-components.vercel.app/docs/components/tailwind-indicator",
  },
  /**
   * Componente `theme-toggle`:
   * Um botão para alternar entre os temas claro, escuro e do sistema, utilizando `next-themes` e Tailwind CSS.
   */
  {
    name: "theme-toggle",
    type: "registry:component",
    description:
      "A theme-toggle component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    title: "theme-toggle",
    author: "MaskSysDev <adminsys-components.vercel.app>",
    dependencies: ["next-themes", "lucide-react"],
    registryDependencies: ["<registryBaseUrl>/utils.json"],
    files: [
      {
        path: "components/layout/toggle/theme-toggle.tsx",
        type: "registry:component",
        target: "src/components/layout/toggle/theme-toggle.tsx",
      },
    ],
    docs: "https://adminsys-components.vercel.app/docs/components/theme-toggle",
  },
  /**
   * Componente `toggle-theme`:
   * Similar ao `theme-toggle`, oferece funcionalidade de alternância de tema com um design ligeiramente diferente.
   */
  {
    name: "toggle-theme",
    type: "registry:component",
    description:
      "A toggle-theme component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    title: "toggle-theme",
    author: "MaskSysDev <adminsys-components.vercel.app>",
    dependencies: ["next-themes", "lucide-react"],
    registryDependencies: ["<registryBaseUrl>/utils.json", "button"],
    files: [
      {
        path: "components/layout/toggle/toggle-theme.tsx",
        type: "registry:component",
        target: "src/components/layout/toggle/toggle-theme.tsx",
      },
    ],
    docs: "https://adminsys-components.vercel.app/docs/components/toggle-theme",
  },
]
