import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os hooks personalizados do projeto.
 * Cada objeto no array representa um hook e suas propriedades, como nome, tipo,
 * título e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`,
 * permitindo a organização e o acesso centralizado aos hooks.
 */
export const hook: Registry["items"] = [
  /**
   * Hook `use-mobile`:
   * Um hook para detectar o estado mobile (se o dispositivo é móvel ou não).
   */
  {
    name: "use-mobile",
    type: "registry:hook",
    title: "Mobile State Hook",
    files: [
      {
        path: "src/hooks/use-mobile.ts",
        type: "registry:hook",
      },
    ],
  },
]
