import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os componentes de exemplo do projeto.
 * Cada objeto no array representa um exemplo e suas propriedades, como nome, tipo,
 * dependências de registro e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`,
 * permitindo a demonstração e visualização dos componentes principais.
 */
export const examples: Registry["items"] = [
  /**
   * Exemplo `sitesys-demo`:
   * Demonstra o uso do componente `sitesys`.
   */
  {
    name: "sitesys",
    type: "registry:example",
    dependencies: ["zod"],
    registryDependencies: [
      "<registryBaseUrl>/site-layout.json",
      "<registryBaseUrl>/logo-sitesys.json",
    ],
    envVars: {
      NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    },
    files: [
      {
        path: "examples/sitesys/app/layout.tsx",
        type: "registry:example",
        target: "src/app/layout.tsx",
      },
      {
        path: "examples/sitesys/app/(home)/layout.tsx",
        type: "registry:example",
        target: "src/app/(home)/layout.tsx",
      },
      {
        path: "examples/sitesys/app/(home)/page.tsx",
        type: "registry:example",
        target: "src/app/(home)/page.tsx",
      },
      {
        path: "examples/sitesys/config/types/index.ts",
        type: "registry:example",
        target: "src/config/types/index.ts",
      },
      {
        path: "examples/sitesys/config/validation/env.schema.ts",
        type: "registry:example",
        target: "src/config/validation/env.schema.ts",
      },
      {
        path: "examples/sitesys/config/validation/site-config.schema.ts",
        type: "registry:example",
        target: "src/config/validation/site-config.schema.ts",
      },
      {
        path: "examples/sitesys/config/env.ts",
        type: "registry:example",
        target: "src/config/env.ts",
      },
      {
        path: "examples/sitesys/config/site-config.tsx",
        type: "registry:example",
        target: "src/config/site-config.tsx",
      },
    ],
  },
  /**
   * Exemplo `banner-demo`:
   * Demonstra o uso do componente `banner`.
   */
  {
    name: "banner-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/banner.json"],
    files: [
      {
        path: "examples/components/layout/banner/banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `container-demo`:
   * Demonstra o uso do componente `container`.
   */
  {
    name: "container-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/container.json"],
    files: [
      {
        path: "examples/components/layout/container/container-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `footer-01-demo`:
   * Demonstra o uso do componente `footer-01`.
   */
  {
    name: "footer-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/footer-01.json"],
    files: [
      {
        path: "examples/components/layout/footer/footer-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `hero-01-demo`:
   * Demonstra o uso do componente `hero-01`.
   */
  {
    name: "hero-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/hero-01.json"],
    files: [
      {
        path: "examples/components/layout/hero/hero-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `icons-demo`:
   * Demonstra o uso do componente `icons`.
   */
  {
    name: "icons-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/icons.json"],
    files: [
      {
        path: "examples/components/layout/icons/icons-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-adminsys-demo`:
   * Demonstra o uso do componente `logo-adminsys`.
   */
  {
    name: "logo-adminsys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-adminsys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-adminsys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-docsys-demo`:
   * Demonstra o uso do componente `logo-docsys`.
   */
  {
    name: "logo-docsys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-docsys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-docsys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-sitesys-demo`:
   * Demonstra o uso do componente `logo-sitesys`.
   */
  {
    name: "logo-sitesys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-sitesys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-sitesys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `navbar-01-demo`:
   * Demonstra o uso do componente `navbar-01`.
   */
  {
    name: "navbar-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/navbar-01.json"],
    files: [
      {
        path: "examples/components/layout/navbar/navbar-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `not-found-demo`:
   * Demonstra o uso do componente `not-found`.
   */
  {
    name: "not-found-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/not-found.json"],
    files: [
      {
        path: "examples/components/layout/not-found/not-found-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `typography-demo`:
   * Demonstra o uso do componente `typography`.
   */
  {
    name: "typography-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/typography.json"],
    files: [
      {
        path: "examples/components/layout/typography/typography-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `social-icon-link-demo`:
   * Demonstra o uso do componente `social-icon-link`.
   */
  {
    name: "social-icon-link-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/social-icon-link.json"],
    files: [
      {
        path: "examples/components/layout/social/social-icon-link-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `tailwind-indicator-demo`:
   * Demonstra o uso do componente `tailwind-indicator`.
   */
  {
    name: "tailwind-indicator-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/tailwind-indicator.json"],
    files: [
      {
        path: "examples/components/dev/tailwind-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `theme-toggle-demo`:
   * Demonstra o uso do componente `theme-toggle` para alternância de temas.
   */
  {
    name: "theme-toggle-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/theme-toggle.json"],
    files: [
      {
        path: "examples/components/layout/toggle/theme-toggle-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `toggle-theme-demo`:
   * Demonstra o uso do componente `toggle-theme` para alternância de temas.
   */
  {
    name: "toggle-theme-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/toggle-theme.json"],
    files: [
      {
        path: "examples/components/layout/toggle/toggle-theme-demo.tsx",
        type: "registry:example",
      },
    ],
  },
]
