import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os componentes de exemplo do projeto.
 * Cada objeto no array representa um exemplo e suas propriedades, como nome, tipo,
 * dependências de registro e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`,
 * permitindo a demonstração e visualização dos componentes principais.
 */
export const examples: Registry["items"] = [
  /**
   * Exemplo `form-auth-demo`:
   * Demonstra o uso do componente `form-auth`.
   */
  {
    name: "form-auth-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/form-auth.json"],
    files: [
      {
        path: "examples/components/auth/form/form-auth-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `dropdown-user-demo`:
   * Demonstra o uso do componente `dropdown-user`.
   */
  {
    name: "dropdown-user-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/dropdown-user.json"],
    files: [
      {
        path: "examples/components/auth/dropdown/dropdown-user-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `admin-navbar-demo`:
   * Demonstra o uso do componente `admin-navbar`.
   */
  {
    name: "admin-navbar-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/admin-navbar.json"],
    files: [
      {
        path: "examples/components/layout/navbar/admin-navbar-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "banner-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/banner.json"],
    files: [
      {
        path: "examples/components/layout/banner/banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `footer-01-demo`:
   * Demonstra o uso do componente `footer-01`.
   */
  {
    name: "footer-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/footer-01.json"],
    files: [
      {
        path: "examples/components/layout/footer/footer-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `hero-01-demo`:
   * Demonstra o uso do componente `hero-01`.
   */
  {
    name: "hero-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/hero-01.json"],
    files: [
      {
        path: "examples/components/layout/hero/hero-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `icons-demo`:
   * Demonstra o uso do componente `icons`.
   */
  {
    name: "icons-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/icons.json"],
    files: [
      {
        path: "examples/components/layout/icons/icons-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `loading-spinner-demo`:
   * Demonstra o uso do componente `loading-spinner`.
   */
  {
    name: "loading-spinner-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/loading-spinner.json"],
    files: [
      {
        path: "examples/components/layout/loading/loading-spinner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-adminsys-demo`:
   * Demonstra o uso do componente `logo-adminsys`.
   */
  {
    name: "logo-adminsys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-adminsys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-adminsys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-docsys-demo`:
   * Demonstra o uso do componente `logo-docsys`.
   */
  {
    name: "logo-docsys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-docsys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-docsys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `logo-sitesys-demo`:
   * Demonstra o uso do componente `logo-sitesys`.
   */
  {
    name: "logo-sitesys-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/logo-sitesys.json"],
    files: [
      {
        path: "examples/components/layout/logo/logo-sitesys-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `navbar-01-demo`:
   * Demonstra o uso do componente `navbar-01`.
   */
  {
    name: "navbar-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/navbar-01.json"],
    files: [
      {
        path: "examples/components/layout/navbar/navbar-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `navbar-auth-01-demo`:
   * Demonstra o uso do componente `navbar-auth-01`.
   */
  {
    name: "navbar-auth-01-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/navbar-auth-01.json"],
    files: [
      {
        path: "examples/components/layout/navbar/navbar-auth-01-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `not-found-demo`:
   * Demonstra o uso do componente `not-found`.
   */
  {
    name: "not-found-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/not-found.json"],
    files: [
      {
        path: "examples/components/layout/not-found/not-found-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `typography-demo`:
   * Demonstra o uso do componente `typography`.
   */
  {
    name: "typography-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/typography.json"],
    files: [
      {
        path: "examples/components/layout/typography/typography-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `social-icon-link-demo`:
   * Demonstra o uso do componente `social-icon-link`.
   */
  {
    name: "social-icon-link-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/social-icon-link.json"],
    files: [
      {
        path: "examples/components/layout/social/social-icon-link-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `tailwind-indicator-demo`:
   * Demonstra o uso do componente `tailwind-indicator`.
   */
  {
    name: "tailwind-indicator-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/tailwind-indicator.json"],
    files: [
      {
        path: "examples/components/dev/tailwind-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `theme-toggle-demo`:
   * Demonstra o uso do componente `theme-toggle` para alternância de temas.
   */
  {
    name: "theme-toggle-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/theme-toggle.json"],
    files: [
      {
        path: "examples/components/layout/toggle/theme-toggle-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `toggle-theme-demo`:
   * Demonstra o uso do componente `toggle-theme` para alternância de temas.
   */
  {
    name: "toggle-theme-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/toggle-theme.json"],
    files: [
      {
        path: "examples/components/layout/toggle/toggle-theme-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Examples Components Shared
   */
  {
    name: "alert-error-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/alert-error.json"],
    files: [
      {
        path: "examples/components/shared/alert/alert-error-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "alert-info-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/alert-info.json"],
    files: [
      {
        path: "examples/components/shared/alert/alert-info-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "alert-success-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/alert-success.json"],
    files: [
      {
        path: "examples/components/shared/alert/alert-success-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "alert-warn-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/alert-warn.json"],
    files: [
      {
        path: "examples/components/shared/alert/alert-warn-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "container-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/container.json"],
    files: [
      {
        path: "examples/components/shared/container/container-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  {
    name: "password-input-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/password-input.json"],
    files: [
      {
        path: "examples/components/shared/form/password-input-demo.tsx",
        type: "registry:example",
      },
    ],
  },
]
