import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os componentes de UI do projeto.
 * Cada objeto no array representa um componente e suas propriedades, como nome, tipo, descrição,
 * autor, dependências e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`.
 */
export const components: Registry["items"] = [
  /**
   * Exemplo `adminsys-demo`:
   * Demonstra o uso do componente `adminsys`.
   */
  {
    name: "adminsys-auth",
    type: "registry:block",
    dependencies: ["zod"],
    registryDependencies: [
      "alert-dialog",
      "switch",
      "<registryBaseUrl>/adminsys.json",
      "<registryBaseUrl>/form-auth.json",
      "<registryBaseUrl>/auth-layout.json",
    ],
    files: [
      {
        path: "examples/adminsys-auth/app/(home)/layout.tsx",
        type: "registry:file",
        target: "src/app/(home)/layout.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/error/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/error/page.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/forgot-password/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/forgot-password/page.tsx",
      },
      {
        path: "components/auth/form/forgot-password-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/forgot-password-form.tsx",
      },
      {
        path: "validations/auth/forgot-password.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/forgot-password.schema.ts",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/new-verification/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/new-verification/page.tsx",
      },
      {
        path: "components/auth/form/new-verification-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/new-verification-form.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/reset-password/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/reset-password/page.tsx",
      },
      {
        path: "components/auth/form/reset-password-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/reset-password-form.tsx",
      },
      {
        path: "validations/auth/reset-password.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/reset-password.schema.ts",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/sign-in/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/sign-in/page.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/auth/sign-up/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/auth/sign-up/page.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/privacy-policy/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/privacy-policy/page.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/terms-of-service/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/terms-of-service/page.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/settings/layout.tsx",
        type: "registry:file",
        target: "src/app/(home)/settings/layout.tsx",
      },
      {
        path: "examples/adminsys-auth/app/(home)/settings/account/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/settings/account/page.tsx",
      },
      {
        path: "components/auth/form/account-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/account-form.tsx",
      },
      {
        path: "components/auth/form/account-image-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/account-image-form.tsx",
      },
      {
        path: "components/auth/form/delete-account-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/delete-account-form.tsx",
      },
      {
        path: "validations/auth/account.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/account.schema.ts",
      },
      {
        path: "examples/adminsys-auth/app/(home)/settings/profile/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/settings/profile/page.tsx",
      },
      {
        path: "components/auth/card/card-user-profile.tsx",
        type: "registry:component",
        target: "src/components/auth/card/card-user-profile.tsx",
      },
    ],
  },
  /**
   * Exemplo `adminsys-demo`:
   * Demonstra o uso do componente `adminsys`.
   */
  {
    name: "adminsys",
    type: "registry:block",
    dependencies: ["zod"],
    registryDependencies: [
      "<registryBaseUrl>/admin-layout.json",
      "<registryBaseUrl>/typography.json",
      "<registryBaseUrl>/not-found.json",
      "<registryBaseUrl>/site-layout.json",
      "<registryBaseUrl>/hero-01.json",
      "<registryBaseUrl>/icons.json",
      "<registryBaseUrl>/logo-adminsys.json",
      "<registryBaseUrl>/metadata.json",
    ],
    envVars: {
      NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    },
    files: [
      {
        path: "examples/adminsys/app/layout.tsx",
        type: "registry:file",
        target: "src/app/layout.tsx",
      },
      {
        path: "examples/adminsys/app/not-found.tsx",
        type: "registry:file",
        target: "src/app/not-found.tsx",
      },
      {
        path: "examples/adminsys/app/sitemap.ts",
        type: "registry:file",
        target: "src/app/sitemap.ts",
      },
      {
        path: "examples/adminsys/app/(home)/layout.tsx",
        type: "registry:file",
        target: "src/app/(home)/layout.tsx",
      },
      {
        path: "examples/adminsys/app/(home)/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/page.tsx",
      },
      {
        path: "examples/adminsys/config/types/index.ts",
        type: "registry:file",
        target: "src/config/types/index.ts",
      },
      {
        path: "examples/adminsys/config/validation/env.schema.ts",
        type: "registry:file",
        target: "src/config/validation/env.schema.ts",
      },
      {
        path: "examples/adminsys/config/validation/site-config.schema.ts",
        type: "registry:file",
        target: "src/config/validation/site-config.schema.ts",
      },
      {
        path: "examples/adminsys/config/env.ts",
        type: "registry:file",
        target: "src/config/env.ts",
      },
      {
        path: "examples/adminsys/config/site-config.tsx",
        type: "registry:file",
        target: "src/config/site-config.tsx",
      },
      {
        path: "examples/adminsys/app/(admin)/admin/layout.tsx",
        type: "registry:file",
        target: "src/app/(admin)/admin/layout.tsx",
      },
      {
        path: "examples/adminsys/app/(admin)/admin/dashboard/page.tsx",
        type: "registry:file",
        target: "src/app/(admin)/admin/dashboard/page.tsx",
      },
      {
        path: "examples/adminsys/app/(admin)/admin/folder-01/submenu-01/page.tsx",
        type: "registry:file",
        target: "src/app/(admin)/admin/folder-01/submenu-01/page.tsx",
      },
      {
        path: "examples/adminsys/app/(admin)/admin/folder-01/submenu-02/page.tsx",
        type: "registry:file",
        target: "src/app/(admin)/admin/folder-01/submenu-02/page.tsx",
      },
    ],
  },
  /**
   * Exemplo `sitesys-demo`:
   * Demonstra o uso do componente `sitesys`.
   */
  {
    name: "sitesys",
    type: "registry:block",
    dependencies: ["zod"],
    registryDependencies: [
      "<registryBaseUrl>/site-layout.json",
      "<registryBaseUrl>/hero-01.json",
      "<registryBaseUrl>/icons.json",
      "<registryBaseUrl>/logo-sitesys.json",
      "<registryBaseUrl>/metadata.json",
    ],
    envVars: {
      NEXT_PUBLIC_APP_URL: "http://localhost:3000",
    },
    files: [
      {
        path: "examples/sitesys/app/layout.tsx",
        type: "registry:file",
        target: "src/app/layout.tsx",
      },
      {
        path: "examples/sitesys/app/sitemap.ts",
        type: "registry:file",
        target: "src/app/sitemap.ts",
      },
      {
        path: "examples/sitesys/app/(home)/layout.tsx",
        type: "registry:file",
        target: "src/app/(home)/layout.tsx",
      },
      {
        path: "examples/sitesys/app/(home)/page.tsx",
        type: "registry:file",
        target: "src/app/(home)/page.tsx",
      },
      {
        path: "examples/sitesys/config/types/index.ts",
        type: "registry:file",
        target: "src/config/types/index.ts",
      },
      {
        path: "examples/sitesys/config/validation/env.schema.ts",
        type: "registry:file",
        target: "src/config/validation/env.schema.ts",
      },
      {
        path: "examples/sitesys/config/validation/site-config.schema.ts",
        type: "registry:file",
        target: "src/config/validation/site-config.schema.ts",
      },
      {
        path: "examples/sitesys/config/env.ts",
        type: "registry:file",
        target: "src/config/env.ts",
      },
      {
        path: "examples/sitesys/config/site-config.tsx",
        type: "registry:file",
        target: "src/config/site-config.tsx",
      },
    ],
  },
  /**
   * Componente `dropdown-user`:
   * Um componente de dropdown-user.
   */
  {
    name: "dropdown-user",
    type: "registry:component",
    description: "A dropdown-user component.",
    title: "dropdown-user",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/auth/dropdown/dropdown-user.tsx",
        type: "registry:component",
        target: "src/components/auth/dropdown/dropdown-user.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/auth/dropdown#dropdown-user",
  },
  /**
   * Componente `form-auth`:
   * Um componente de form-auth.
   */
  {
    name: "form-auth",
    type: "registry:component",
    description: "A form-auth component.",
    title: "form-auth",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "button",
      "card",
      "dialog",
      "form",
      "scroll-area",
      "tabs",
      "sonner",
      "<registryBaseUrl>/alert-error.json",
      "<registryBaseUrl>/alert-success.json",
      "<registryBaseUrl>/icons.json",
      "<registryBaseUrl>/loading-spinner.json",
      "<registryBaseUrl>/password-input.json",
      "<registryBaseUrl>/sanitize.json",
    ],
    files: [
      {
        path: "components/auth/card/card-auth-wrapper.tsx",
        type: "registry:component",
        target: "src/components/auth/card/card-auth-wrapper.tsx",
      },
      {
        path: "components/auth/dialog/terms-and-policy-dialog.tsx",
        type: "registry:component",
        target: "src/components/auth/dialog/terms-and-policy-dialog.tsx",
      },
      {
        path: "components/auth/form/social-login.tsx",
        type: "registry:component",
        target: "src/components/auth/form/social-login.tsx",
      },
      {
        path: "components/auth/form/sign-in-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/sign-in-form.tsx",
      },
      {
        path: "validations/auth/auth-base.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/auth-base.schema.ts",
      },
      {
        path: "validations/auth/sign-in.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/sign-in.schema.ts",
      },
      {
        path: "components/auth/form/sign-up-form.tsx",
        type: "registry:component",
        target: "src/components/auth/form/sign-up-form.tsx",
      },
      {
        path: "validations/auth/sign-up.schema.ts",
        type: "registry:component",
        target: "src/validations/auth/sign-up.schema.ts",
      },
      {
        path: "components/auth/form/form-auth.tsx",
        type: "registry:component",
        target: "src/components/auth/form/form-auth.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/auth/form#form-auth",
  },
  /**
   * Componente `admin-navbar`:
   * Um componente de admin-navbar.
   */
  {
    name: "admin-navbar",
    type: "registry:component",
    description: "A admin-navbar component.",
    title: "admin-navbar",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "sidebar",
      "<registryBaseUrl>/container.json",
      "<registryBaseUrl>/dropdown-user.json",
      "<registryBaseUrl>/toggle-theme.json",
    ],
    files: [
      {
        path: "components/layout/navbar/admin-navbar.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/admin-navbar.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/navbar#admin-navbar",
  },
  /**
   * Componente `admin-sidebar`:
   * Um componente de admin-sidebar.
   */
  {
    name: "admin-sidebar",
    type: "registry:component",
    description: "A admin-sidebar component.",
    title: "admin-sidebar",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "avatar",
      "dropdown-menu",
      "sidebar",
      "scroll-area",
      "collapsible",
      "<registryBaseUrl>/logo-adminsys.json",
    ],
    files: [
      {
        path: "components/layout/sidebar/inc/part/sidebar-menu-folder.tsx",
        type: "registry:component",
        target:
          "src/components/layout/sidebar/inc/part/sidebar-menu-folder.tsx",
      },
      {
        path: "components/layout/sidebar/inc/part/sidebar-menu-link.tsx",
        type: "registry:component",
        target: "src/components/layout/sidebar/inc/part/sidebar-menu-link.tsx",
      },
      {
        path: "components/layout/sidebar/inc/part/sidebar-submenu-link.tsx",
        type: "registry:component",
        target:
          "src/components/layout/sidebar/inc/part/sidebar-submenu-link.tsx",
      },
      {
        path: "components/layout/sidebar/inc/sidebar-nav-main.tsx",
        type: "registry:component",
        target: "src/components/layout/sidebar/inc/sidebar-nav-main.tsx",
      },
      {
        path: "components/layout/sidebar/inc/sidebar-nav-secondary.tsx",
        type: "registry:component",
        target: "src/components/layout/sidebar/inc/sidebar-nav-secondary.tsx",
      },
      {
        path: "components/layout/sidebar/inc/sidebar-nav-user.tsx",
        type: "registry:component",
        target: "src/components/layout/sidebar/inc/sidebar-nav-user.tsx",
      },
      {
        path: "components/layout/sidebar/admin-sidebar.tsx",
        type: "registry:component",
        target: "src/components/layout/sidebar/admin-sidebar.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/sidebar#admin-sidebar",
  },
  /**
   * Componente `admin-layout`:
   * Um componente de admin-layout.
   */
  {
    name: "admin-layout",
    type: "registry:component",
    description: "A admin-layout component.",
    title: "admin-layout",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "sidebar",
      "sonner",
      "<registryBaseUrl>/tailwind-indicator.json",
      "<registryBaseUrl>/admin-navbar.json",
      "<registryBaseUrl>/admin-sidebar.json",
    ],
    files: [
      {
        path: "components/layout/admin-layout/index.tsx",
        type: "registry:component",
        target: "src/components/layout/admin-layout/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/admin-layout",
  },
  /**
   * Componente `banner`:
   * Um componente de banner.
   */
  {
    name: "banner",
    type: "registry:component",
    description: "A banner component.",
    title: "banner",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "badge",
      "button",
      "<registryBaseUrl>/container.json",
    ],
    files: [
      {
        path: "components/layout/banner/index.tsx",
        type: "registry:component",
        target: "src/components/layout/banner/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/banner",
  },
  /**
   * Componente `footer-01`:
   * Um componente de footer-01.
   */
  {
    name: "footer-01",
    type: "registry:component",
    description: "A footer-01 component.",
    title: "footer-01",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "<registryBaseUrl>/container.json",
      "<registryBaseUrl>/social-icon-link.json",
    ],
    files: [
      {
        path: "components/layout/footer/footer-01.tsx",
        type: "registry:component",
        target: "src/components/layout/footer/footer-01.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/footer#footer-01",
  },
  /**
   * Componente `hero-01`:
   * Um componente de hero-01.
   */
  {
    name: "hero-01",
    type: "registry:component",
    description: "A hero-01 component.",
    title: "hero",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["<registryBaseUrl>/banner.json"],
    files: [
      {
        path: "components/layout/hero/hero-01.tsx",
        type: "registry:component",
        target: "src/components/layout/hero/hero-01.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/hero#hero-01",
  },
  /**
   * Componente `navbar-01`:
   * Um componente de navbar-01.
   */
  {
    name: "navbar-01",
    type: "registry:component",
    description: "A navbar-01 component.",
    title: "navbar-01",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "button",
      "sidebar",
      "navigation-menu",
      "<registryBaseUrl>/container.json",
    ],
    files: [
      {
        path: "components/layout/navbar/inc/nav-main.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-main.tsx",
      },
      {
        path: "components/layout/navbar/inc/nav-mobile.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-mobile.tsx",
      },
      {
        path: "components/layout/navbar/inc/nav-system.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-system.tsx",
      },
      {
        path: "components/layout/navbar/types/index.ts",
        type: "registry:component",
        target: "src/components/layout/navbar/types/index.ts",
      },
      {
        path: "components/layout/navbar/navbar-01.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/navbar-01.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/logo#navbar-01",
  },
  /**
   * Componente `navbar-auth-01`:
   * Um componente de navbar-auth-01.
   */
  {
    name: "navbar-auth-01",
    type: "registry:component",
    description: "A navbar-auth-01 component.",
    title: "navbar-auth-01",
    author: "<author> <<authorUrl>>",
    registryDependencies: [
      "button",
      "sidebar",
      "navigation-menu",
      "<registryBaseUrl>/container.json",
    ],
    files: [
      {
        path: "components/layout/navbar/inc/nav-main-auth.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-main-auth.tsx",
      },
      {
        path: "components/layout/navbar/inc/nav-mobile-auth.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-mobile-auth.tsx",
      },
      {
        path: "components/layout/navbar/inc/nav-system.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/inc/nav-system.tsx",
      },
      {
        path: "components/layout/navbar/types/index.ts",
        type: "registry:component",
        target: "src/components/layout/navbar/types/index.ts",
      },
      {
        path: "components/layout/navbar/navbar-auth-01.tsx",
        type: "registry:component",
        target: "src/components/layout/navbar/navbar-auth-01.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/logo#navbar-auth-01",
  },
  /**
   * Componente `auth-layout`:
   * Um componente de auth-layout.
   */
  {
    name: "auth-layout",
    type: "registry:component",
    description: "A auth-layout component.",
    title: "auth-layout",
    author: "<author> <<authorUrl>>",
    dependencies: ["next-themes"],
    registryDependencies: [
      "sidebar",
      "sonner",
      "<registryBaseUrl>/tailwind-indicator.json",
      "<registryBaseUrl>/navbar-auth-01.json",
      "<registryBaseUrl>/footer-01.json",
    ],
    files: [
      {
        path: "components/layout/auth-layout/index.tsx",
        type: "registry:component",
        target: "src/components/layout/auth-layout/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/auth-layout",
  },
  /**
   * Componente `site-layout`:
   * Um componente de site-layout.
   */
  {
    name: "site-layout",
    type: "registry:component",
    description: "A site-layout component.",
    title: "site-layout",
    author: "<author> <<authorUrl>>",
    dependencies: ["next-themes"],
    registryDependencies: [
      "sidebar",
      "sonner",
      "<registryBaseUrl>/tailwind-indicator.json",
      "<registryBaseUrl>/navbar-01.json",
      "<registryBaseUrl>/footer-01.json",
    ],
    files: [
      {
        path: "components/layout/site-layout/index.tsx",
        type: "registry:component",
        target: "src/components/layout/site-layout/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/layout/site-layout",
  },
  /**
   * Componente `tailwind-indicator`:
   * Um indicador visual para ambientes de desenvolvimento que mostra o breakpoint atual do Tailwind CSS.
   */
  {
    name: "tailwind-indicator",
    type: "registry:component",
    description: "A tailwind-indicator component.",
    title: "tailwind-indicator",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/dev/tailwind-indicator.tsx",
        type: "registry:component",
        target: "src/components/dev/tailwind-indicator.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/dev/tailwind-indicator",
  },
  /**
   * Components Shared
   */

  /* alert */
  {
    name: "alert-error",
    type: "registry:component",
    description: "A alert-error component.",
    title: "alert-error",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["alert"],
    files: [
      {
        path: "components/shared/alert/alert-error.tsx",
        type: "registry:component",
        target: "src/components/shared/alert/alert-error.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/alert#alert-error",
  },
  {
    name: "alert-info",
    type: "registry:component",
    description: "A alert-info component.",
    title: "alert-info",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["alert"],
    files: [
      {
        path: "components/shared/alert/alert-info.tsx",
        type: "registry:component",
        target: "src/components/shared/alert/alert-info.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/alert#alert-info",
  },
  {
    name: "alert-success",
    type: "registry:component",
    description: "A alert-success component.",
    title: "alert-success",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["alert"],
    files: [
      {
        path: "components/shared/alert/alert-success.tsx",
        type: "registry:component",
        target: "src/components/shared/alert/alert-success.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/alert#alert-success",
  },
  {
    name: "alert-warn",
    type: "registry:component",
    description: "A alert-warn component.",
    title: "alert-warn",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["alert"],
    files: [
      {
        path: "components/shared/alert/alert-warn.tsx",
        type: "registry:component",
        target: "src/components/shared/alert/alert-warn.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/alert#alert-warn",
  },

  /* container */
  {
    name: "container",
    type: "registry:component",
    description: "A container component.",
    title: "container",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/container/index.tsx",
        type: "registry:component",
        target: "src/components/shared/container/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/container",
  },

  /* form */
  {
    name: "password-input",
    type: "registry:component",
    description: "A password-input component.",
    title: "password-input",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["button", "input"],
    files: [
      {
        path: "components/shared/form/password-input/index.tsx",
        type: "registry:component",
        target: "src/components/shared/form/password-input/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/form#password-input",
  },

  /* icons */
  {
    name: "icons",
    type: "registry:component",
    description: "A icons component.",
    title: "icons",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/icons/index.tsx",
        type: "registry:component",
        target: "src/components/shared/icons/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/icons",
  },

  /* loading */
  {
    name: "loading-spinner",
    type: "registry:component",
    description: "A loading-spinner component.",
    title: "loading-spinner",
    author: "<author> <<authorUrl>>",
    registryDependencies: ["spinner"],
    files: [
      {
        path: "components/shared/loading/loading-spinner.tsx",
        type: "registry:component",
        target: "src/components/shared/loading/loading-spinner.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/loading#loading-spinner",
  },

  /* logo */
  {
    name: "logo-adminsys",
    type: "registry:component",
    description: "A logo-adminsys component.",
    title: "logo-adminsys",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/logo/logo-adminsys.tsx",
        type: "registry:component",
        target: "src/components/shared/logo/logo-adminsys.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/logo#logo-adminsys",
  },
  {
    name: "logo-docsys",
    type: "registry:component",
    description: "A logo-docsys component.",
    title: "logo-docsys",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/logo/logo-docsys.tsx",
        type: "registry:component",
        target: "src/components/shared/logo/logo-docsys.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/logo#logo-docsys",
  },
  {
    name: "logo-sitesys",
    type: "registry:component",
    description: "A logo-sitesys component.",
    title: "logo-sitesys",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/logo/logo-sitesys.tsx",
        type: "registry:component",
        target: "src/components/shared/logo/logo-sitesys.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/logo#logo-sitesys",
  },

  /* not-found */
  {
    name: "not-found",
    type: "registry:component",
    description: "A not-found component.",
    title: "not-found",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/not-found/index.tsx",
        type: "registry:component",
        target: "src/components/shared/not-found/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/not-found",
  },

  /* provider */
  {
    name: "theme-provider",
    type: "registry:component",
    description: "A theme-provider component.",
    title: "theme-provider",
    author: "<author> <<authorUrl>>",
    dependencies: ["next-themes"],
    files: [
      {
        path: "components/shared/provider/theme-provider.tsx",
        type: "registry:component",
        target: "src/components/shared/provider/theme-provider.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/provider#theme-provider",
  },

  /* social */
  {
    name: "social-icon-link",
    type: "registry:component",
    description: "A social-icon-link component.",
    title: "social-icon-link",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/social/social-icon-link.tsx",
        type: "registry:component",
        target: "src/components/shared/social/social-icon-link.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/social#social-icon-link",
  },

  /* toggle */
  {
    name: "theme-toggle",
    type: "registry:component",
    description:
      "A theme-toggle component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    title: "theme-toggle",
    author: "<author> <<authorUrl>>",
    dependencies: ["next-themes"],
    files: [
      {
        path: "components/shared/toggle/theme-toggle.tsx",
        type: "registry:component",
        target: "src/components/shared/toggle/theme-toggle.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/toggle#toggle-theme",
  },
  {
    name: "toggle-theme",
    type: "registry:component",
    description:
      "A toggle-theme component with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    title: "toggle-theme",
    author: "<author> <<authorUrl>>",
    dependencies: ["next-themes"],
    registryDependencies: ["button"],
    files: [
      {
        path: "components/shared/toggle/toggle-theme.tsx",
        type: "registry:component",
        target: "src/components/shared/toggle/toggle-theme.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/toggle#toggle-theme",
  },

  /* typography */
  {
    name: "typography",
    type: "registry:component",
    description: "A typography component.",
    title: "typography",
    author: "<author> <<authorUrl>>",
    files: [
      {
        path: "components/shared/typography/index.tsx",
        type: "registry:component",
        target: "src/components/shared/typography/index.tsx",
      },
    ],
    docs: "<baseUrl>/docs/components/shared/typography",
  },
]
