import type { Registry } from "shadcn/schema"

/**
 * Este arquivo define os metadados para os componentes de exemplo do projeto.
 * Cada objeto no array representa um exemplo e suas propriedades, como nome, tipo,
 * dependências de registro e caminhos de arquivo. Essas informações são usadas pelo processo
 * de construção do registro para gerar arquivos como `index.tsx` e `registry.autogenerated.json`,
 * permitindo a demonstração e visualização dos componentes principais.
 */
export const examples: Registry["items"] = [
  /**
   * Exemplo `banner-demo`:
   * Demonstra o uso do componente `banner`.
   */
  {
    name: "banner-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/banner.json"],
    files: [
      {
        path: "examples/components/layout/banner/banner-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `tailwind-indicator-demo`:
   * Demonstra o uso do componente `tailwind-indicator`.
   */
  {
    name: "tailwind-indicator-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/tailwind-indicator.json"],
    files: [
      {
        path: "examples/components/dev/tailwind-indicator-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `theme-toggle-demo`:
   * Demonstra o uso do componente `theme-toggle` para alternância de temas.
   */
  {
    name: "theme-toggle-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/theme-toggle.json"],
    files: [
      {
        path: "examples/components/layout/toggle/theme-toggle-demo.tsx",
        type: "registry:example",
      },
    ],
  },
  /**
   * Exemplo `toggle-theme-demo`:
   * Demonstra o uso do componente `toggle-theme` para alternância de temas.
   */
  {
    name: "toggle-theme-demo",
    type: "registry:example",
    registryDependencies: ["<registryBaseUrl>/toggle-theme.json"],
    files: [
      {
        path: "examples/components/layout/toggle/toggle-theme-demo.tsx",
        type: "registry:example",
      },
    ],
  },
]
